" Gerenciador de plugins
call plug#begin('~/.vim/autoload/plug/start')

" Plugins essenciais
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'honza/vim-snippets'
Plug 'Shougo/neosnippet-snippets'
Plug 'Shougo/neosnippet.vim'
Plug 'SirVer/ultisnips'
Plug 'zenorocha/dracula-theme'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'Yggdroot/indentLine'
Plug 'Shougo/vimshell.vim'
Plug 'scrooloose/nerdtree'
Plug 'mattn/emmet-vim'
Plug 'Shougo/neocomplete.vim'
Plug 'gmarik/Vundle.vim'
Plug 'jiangmiao/auto-pairs'

call plug#end()

" Configurações do Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='dracula'

" Configurações gerais
syntax on
filetype plugin indent on
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab

" Tema Dracula
set background=dark
colorscheme dracula

" Melhor visualização
set cursorline
set termguicolors
highlight CursorLine cterm=NONE ctermbg=darkgray ctermfg=white guibg=darkgray

" Configurações do Coc
set hidden
set nobackup
set nowritebackup
set updatetime=300
set signcolumn=yes

" Configuração do auto-pairs
let g:AutoPairsMapBS = 1  " Habilitar backspace para apagar pares automaticamente
let g:AutoPairsFlyMode = 1  " Adicionar fechamento automático durante digitação rápida

" Mapeamentos personalizados no modo de inserção
" Ctrl+e: Vai para o final da linha e continua editando
inoremap <C-e> <Esc>A

" Ctrl+a: Vai para o início da linha e continua editando
inoremap <C-a> <Esc>I

" Ctrl+l: Vai pra linha de baixo
inoremap <C-j> <Esc>j

" Ctrl+k: Vai pra linha de cima
inoremap <C-k> <Esc>k

" Ctrl+t: Abre o terminal na vertical
inoremap <C-t> <Esc>:vsp term:///bin/bash<CR>

" Ctrl+n: Abre o NERDTree
inoremap <C-ç> <Esc>:NERDTreeToggle<CR>
